### ISSUE TITLE
Silly Question(s)

### ISSUE THREAD

**Issue by Pantgold** [JerichoFletcher/mechanical-warfare#103]
Okay, ive never played Mindustry with mods before version 104.6
Ive finished the entire game without mods, so I'm not familiar with a lot of the new stuffs

First, Where the frick do I get irons Other than From Seperators?

Second, Where Do I get lava?

Third, Where do I get Uranium(s)?

Thats it for now.

This Is a photo of my Tech tree
https://imgur.com/a/ZJmB14z

**Comment by Pantgold** [comment]
Note : 
i have these mods : 
Advance Content
Extended Unit Arsenal
Mechanical Warfare (This mod)
OhNo Missiles
Multi-lib

**Comment by GlennFolker** [comment]
Thanks for asking the questions; here we go:
- _Iron_ can be mined in Mechanical Warfare custom maps, you should see _Frozen Valley_ in the campaign launch section after _Ground Zero_.
- _Lava_ can be obtained in two ways:
  - By melting stone in _Stone Melter_; or
  - Just pump any _Lava_ source; currently _Volcano_ is the only map with _Lava_
- Same as _Iron_, _Uranium_ is also mined in Mechanical Warfare custom maps. The easiest way is to mine it fron _Volcano_.

**Comment by kapzduke** [comment]
> Thanks for asking the questions; here we go:
> 
> * _Iron_ can be mined in Mechanical Warfare custom maps, you should see _Frozen Valley_ in the campaign launch section after _Ground Zero_.
> * _Lava_ can be obtained in two ways:
>   
>   * By melting stone in _Stone Melter_; or
>   * Just pump any _Lava_ source; currently _Volcano_ is the only map with _Lava_
> * Same as _Iron_, _Uranium_ is also mined in Mechanical Warfare custom maps. The easiest way is to mine it fron _Volcano_.

you can also obtain iron via magnetic sieve, and uranium via molecular dissipator (needs radioactive spore pods tho)
