### ISSUE TITLE
Devastator crashes ny phond

### ISSUE THREAD

**Issue by MIGHTYCLIMBER** [JerichoFletcher/mechanical-warfare#120]
When I tryed to spawn a devastator (via wave)the game crashes,can you fix it

**Comment by GlennFolker** [comment]
it's still in development and wasn't supposed to be spawn... yet.

**Comment by bvcbvc** [comment]
also the mod is huge

**Comment by JerichoFletcher** [comment]
I'll close this issue and revisit it when Devastator is finished.
