### ISSUE TITLE
It just won't work

### ISSUE THREAD

**Issue by CALogan2** [JerichoFletcher/mechanical-warfare#125]
When I try to download this mod on Apple it says that a "type" is missing and that it must be added before the file can be parsed.

**Comment by GlennFolker** [comment]
Man i really need to make issue template.
Mods just don't work on trash like Apple products

**Comment by ThePythonGuy3** [comment]
Better explanation: Scripts made in JavaScript won't work on Apple products because it lacks JavaScript libraries
