### ISSUE TITLE
When for the v6 updaye

### ISSUE THREAD

**Issue by Noxx67** [JerichoFletcher/mechanical-warfare#130]
Its been a while since i am waiting for a v6 and i dont know if its coming or not is it abzndoned or work in progress? Or i have a problem with my version
Cause i play in android

**Comment by JerichoFletcher** [comment]
1. It is currently a WIP, and it's still in its early stage since we're rewriting everything.
2. It would be more proper to ask questions on our [Discord server](https://discord.gg/K3uzNSD) instead of submitting it as an issue report.
