### ISSUE TITLE
There aren't bundle files

### ISSUE THREAD

**Issue by feu-follet** [JerichoFletcher/mechanical-warfare#16]
Could you add bundles  ? I'd like to do the french translation for your mod
Thanks

**Comment by GlennFolker** [comment]
I've created the English bundle. Feel free to fork the 1.4 branch and create French bundle. Thanks for your feedback by the way.

**Comment by JerichoFletcher** [comment]
@feu-follet We have added a new turret (Heat Ray) to the v1.4 branch. You might want to update your bundle. Thanks.

**Comment by GlennFolker** [comment]
@feu-follet And a new effect block (Fire Aura). Thanks.

**Comment by feu-follet** [comment]
[bundle_fr.zip](https://github.com/JerichoFletcher/mechanical-warfare/files/4528632/bundle_fr.zip)
Here is the bundle for french translation (.properties isn't supported, so it's a .zip), I send it because I'm not able to directly upload it. I will add fire aura and heat ray when it will be uploaded.
Thank you

**Comment by GlennFolker** [comment]
Will be included in v1.4. Thanks, really appreciate it.
