### ISSUE TITLE
Hill path

### ISSUE THREAD

**Issue by DatOnePlayer** [JerichoFletcher/mechanical-warfare#35]
It seems it's impassable, knowing not only coal were scarce but also titanium, phantasms way too OP in the level

**Comment by GlennFolker** [comment]
Can you tell me what I should change:
- Ore count;
- Wave Timer;
- Wave difficulty; or
- Enemy fortification?

**Comment by feu-follet** [comment]
It's quite passable globally, just remove chaos array and lich, maybe replace them by units from your mod, but less powerfull

**Comment by DatOnePlayer** [comment]
Ore count, needs scrap and a little bit more of titanium, and nerf phantasm, either the damage or rate of fire that should be nerfed

**Comment by JerichoFletcher** [comment]
We'll do some balancing on v1.5 👍

**Comment by JerichoFletcher** [comment]
Phantasm has been nerfed in v1.5, halved its fire rate and lowered its bullet explosion range. Should now be quite easier to deal with.
