### ISSUE TITLE
Stone overrides other ores

### ISSUE THREAD

**Issue by TenguOnTheTop** [JerichoFletcher/mechanical-warfare#38]
Not sure what causes this, but yeah. Stone resources will override other ores when placing drills, preventing max utilization of resources

**Comment by JerichoFletcher** [comment]
Unfortunately it's some sort of a behavior hardcoded into Mindustry and we are currently not able to override it. Do you think it would be better if stone is mined from a certain reserve (sort of ore) instead of directly from the floor?

**Comment by TenguOnTheTop** [comment]
Maybe? Part of what I like is that it's on every map (well, nearly :p) making it a source of sand , and for lava for waves.

I suppose in a lot of cases it's not too big a deal.

**Comment by JerichoFletcher** [comment]
Yeah, perhaps it's better in its current state. After all, let's hope the workaround does its job :)

**Comment by JerichoFletcher** [comment]
The workaround didn't work, unfortunately. If this issue really bothers a lot of people, then the option left is to add some sort of stone deposit to drill from instead of just stone floor tiles, but it may cause problems with save files already having drills on floor tiles. We'll just wait for now. Sorry :/

**Comment by TenguOnTheTop** [comment]
I guess you could also make it like a cultivator/oil extractor, and have it generate stone wherever, with stone tiles instead improving efficiency?

**Comment by JerichoFletcher** [comment]
Actually, that sounds like a good idea, but we've decided not to add more blocks to v1.5 now that it's approaching its release date. Perhaps we'll do on v1.6?

**Comment by JerichoFletcher** [comment]
We have added a new block dedicated to extract stone, and drills won't be needed to mine them anymore on v1.6, so I think this issue is now considered settled.
