### ISSUE TITLE
After updating

### ISSUE THREAD

**Issue by DatOnePlayer** [JerichoFletcher/mechanical-warfare#53]
I can't use them? It says files missing on certain blocks

**Comment by JerichoFletcher** [comment]
On which ones?

**Comment by feu-follet** [comment]
Oh no textures ?

**Comment by DatOnePlayer** [comment]
![Screenshot_20200522-232905_Mindustry](https://user-images.githubusercontent.com/61370548/82689171-41191380-9c84-11ea-852e-8962230a0dfc.jpg)

**Comment by DatOnePlayer** [comment]
@JerichoFletcher

**Comment by feu-follet** [comment]
What appears when you click details ?

**Comment by feu-follet** [comment]
I don't understand what's wrong for me it works fine

**Comment by DatOnePlayer** [comment]
![Screenshot_20200523-035238_Mindustry](https://user-images.githubusercontent.com/61370548/82708673-0aa1bf80-9ca9-11ea-9d76-7a320230b5bd.jpg)
![Screenshot_20200523-035251_Mindustry](https://user-images.githubusercontent.com/61370548/82708677-0d041980-9ca9-11ea-970b-54a460c14687.jpg)
![Uploading Screenshot_20200523-035258_Mindustry.jpg…]()

**Comment by DatOnePlayer** [comment]
![Screenshot_20200523-035307_Mindustry](https://user-images.githubusercontent.com/61370548/82708682-0fff0a00-9ca9-11ea-8ffa-c8b8958e00a4.jpg)
![Screenshot_20200523-035313_Mindustry](https://user-images.githubusercontent.com/61370548/82708687-1097a080-9ca9-11ea-84c9-6941bcbd57dd.jpg)

**Comment by feu-follet** [comment]
[JerichoFletchermechanical-warfare.zip](https://github.com/JerichoFletcher/mechanical-warfare/files/4670341/JerichoFletchermechanical-warfare.zip)
Try this it's the version I have
Maybe it'll work

**Comment by DatOnePlayer** [comment]
All of them have the same error

**Comment by feu-follet** [comment]
Hmm

**Comment by feu-follet** [comment]
Tell me if my version does work

**Comment by DatOnePlayer** [comment]
I already tried it and it doesn't appear on the list, and after i tried install the mod again it says "the file under the same name is already exist"

**Comment by DatOnePlayer** [comment]
So I can't either delete or add the mod file...

**Comment by DatOnePlayer** [comment]
@feu-follet

**Comment by feu-follet** [comment]
Ok actually the bug is only on computer I don't know why

**Comment by feu-follet** [comment]
Are you on computer ?

**Comment by feu-follet** [comment]
Go in app files and delete the mod

**Comment by feu-follet** [comment]
@DatOnePlayer

**Comment by DatOnePlayer** [comment]
I am on mobile

**Comment by DatOnePlayer** [comment]
> Go in app files and delete the mod

How?

**Comment by feu-follet** [comment]
That's weird

**Comment by feu-follet** [comment]
Internal storage => Android => data => io.anuke.mindustry => files => mods
And then delete mechanical warfare

**Comment by DatOnePlayer** [comment]
Done it three times and still the same

**Comment by DatOnePlayer** [comment]
> Done it three times and still the same

It has missing contents like the screenshot before

**Comment by feu-follet** [comment]
You deleted the file from mods folder and it's still appearing ?

**Comment by DatOnePlayer** [comment]
> You deleted the file from mods folder and it's still appearing ?

No, so with the file you sent me, if use the import file option in mindustry it won't appear, so I have to copy it directly to it's directory, then open it again, and poof, same result, missing contents

**Comment by feu-follet** [comment]
Idk what's happening I'm really sorry I can't help you

**Comment by feu-follet** [comment]
Did you enable other mods ?

**Comment by DatOnePlayer** [comment]
Yes
z0mbiesrock/Diamond-Ore
Garmundo/Extended-unit-arsenal
Ariii/Ku-Mod
xamionex/Opore-Mod
Micoplasma/Raze

And many else, but it works fine and all before I updated to this version

**Comment by DatOnePlayer** [comment]
Addition : none of them are overwriting your mod

**Comment by feu-follet** [comment]
Try without these mods, maybe it'll change something

**Comment by DatOnePlayer** [comment]
> Try without these mods, maybe it'll change something

Okay I try disabling some and it work, and the ones I disabled are my favorites too, hopefully next update I got to play them along with your mod again

**Comment by feu-follet** [comment]
I'm sorry for you, maybe it's because mecanical warfare overrides some vanilla content ?

**Comment by feu-follet** [comment]
I Hope too

**Comment by DatOnePlayer** [comment]
> I'm sorry for you, maybe it's because mecanical warfare overrides some vanilla content ?

None of my used mods override the vanilla content they all got their independent thing

**Comment by feu-follet** [comment]
Didn't find Ariii/Ku-Mod ...
Did you misspell ?

**Comment by DatOnePlayer** [comment]
> Didn't find Ariii/Ku-Mod ...
> Did you misspell ?

Sorry it's with six i's

**Comment by DatOnePlayer** [comment]
Ariiiiii/Ku-Mod

**Comment by JerichoFletcher** [comment]
@DatOnePlayer can you send me the game log? It's in Android\data\io.anuke mindustry, there should be a file named last_log.txt

**Comment by feu-follet** [comment]
Overrides fortress factory

**Comment by feu-follet** [comment]
And I think sprites could also make errors

**Comment by JerichoFletcher** [comment]
I was able to replicate this while also enabling younggam's [multi-lib](https://github.com/younggam/multi-lib). Are there any other mods that also conflicts?

**Comment by JerichoFletcher** [comment]
Browsed through the log file. The error is caused by several turrets that use this mod's item as ammo and custom bullets.

> What throws the error?

The `init()` line.

> Why does it throw the error?

Dunno. Haven't checked the log thoroughly.

**Comment by JerichoFletcher** [comment]
We've found out why it threw the error, and we'll release v1.5.1 to resolve this and #54. Let us know if you find another issue in the current version.
