### ISSUE TITLE
Mod compatability issues?

### ISSUE THREAD

**Issue by TenguOnTheTop** [JerichoFletcher/mechanical-warfare#54]
I dunno if this really is anything I should be posting, cause it's caused by another mod, but multiple turrets crash the game when fired with[ Advanced Content ](https://github.com/EyeOfDarkness/AdvanceContent) enabled. 
![Untitled](https://user-images.githubusercontent.com/56941165/82744343-c65fff00-9d3c-11ea-96a7-521eebe1fef5.png)

Of the turrets I know are affected: Quake, Blow, and Seism. 

As I said, I dunno if this even is an issues that could be fixed, but figured it couldn't hurt to raise awareness.

**Comment by JerichoFletcher** [comment]
Perhaps it's caused by MW and AC both have a lib named "effectlib". I'll try fixing this.

**Comment by TenguOnTheTop** [comment]
Seems to be: I went in and changed the file-name and reference to it accordingly, and tested the Seism, and that worked fine!

TY for the quick response, and apologies for bringing up such a dumb issue.

**Comment by JerichoFletcher** [comment]
We'll try to resolve some issues and wrap everything as release v1.5.1. And hey, don't mind to report and let us know if you find any other problem 👍
