### ISSUE TITLE
New stuffs? Or maybe some contributions?

### ISSUE THREAD

**Issue by DatOnePlayer** [JerichoFletcher/mechanical-warfare#56]
New liquid turret? Or maybe new cheap anti-air energy turret

I can make maps too, if you don't mind can I contribute on map making?

**Comment by feu-follet** [comment]
Yes liquid turret would be nice, specially with acid and lava
Anti air energy turret too

**Comment by DatOnePlayer** [comment]
Can I be your map maker too? I love this mod and wanted to expand it

**Comment by DatOnePlayer** [comment]
@feu-follet 
@JerichoFletcher

**Comment by feu-follet** [comment]
I don't know ...
I'm just translator the creators are JerichoFletcher and GlennFolker

**Comment by feu-follet** [comment]
But I love this mod too and again thank them a lot

**Comment by DatOnePlayer** [comment]
Well I really wanted to help though, but they're jot responding

**Comment by JerichoFletcher** [comment]
Sorry for the late response. We're open to contributions! If you want to add something, fork the newest branch and feel free to add contents you like. We'll review it as soon as you make a pull request. Thanks!

**Comment by DatOnePlayer** [comment]
How to do it??

**Comment by JerichoFletcher** [comment]
@DatOnePlayer if you want to add maps, make sure to include MW contents (wave enemies, turrets). We'll review your map when it's done (and if it's cool we'll include it in campaign!).

**Comment by JerichoFletcher** [comment]
> How to do it?

@DatOnePlayer are you using GitHub on phone or on PC? If you're on PC, there should be a Fork button on the top right. If you're on phone, switch to Desktop version first (scroll to the bottom).

**Comment by feu-follet** [comment]
Hi, so could I do the liquid turret ?
Is waterfall a good name in your opinion ?

**Comment by JerichoFletcher** [comment]
'Waterfall' sounds pretty good, but I feel like it implies that it only shoots water...

**Comment by feu-follet** [comment]
Cascade ?

**Comment by feu-follet** [comment]
I wanna do a new statusEffect "corroded" for the acid, which decreases gradually ennemies speed

**Comment by feu-follet** [comment]
Can I ?

**Comment by feu-follet** [comment]
Why not create a discord server for your mod ?
Because talking through Github is not really convenient

**Comment by DatOnePlayer** [comment]
Jetstream should be the new liquid turret

**Comment by DatOnePlayer** [comment]
And btw, I already add my pull

**Comment by feu-follet** [comment]
Jetstream already exists from whert tex

**Comment by DatOnePlayer** [comment]
Hydrant? Lol

**Comment by feu-follet** [comment]
Isn't cascade a good one ?

**Comment by DatOnePlayer** [comment]
What about Torrent?

**Comment by DatOnePlayer** [comment]
Cascade is good too

**Comment by feu-follet** [comment]
Ok yes torrent is nice

**Comment by GlennFolker** [comment]
I personally like Cascade for the name.

**Comment by feu-follet** [comment]
As you like :)
And is corroded good for status effect ?

**Comment by JerichoFletcher** [comment]
Corroded is used by acid. It applies additional damage (if I'm not wrong).

**Comment by JerichoFletcher** [comment]
> And btw, I already add my pull

@DatOnePlayer I see you made a pull only between the branches in _your_ fork. You should make the pull to the _base_ repo (and by _base_ I mean _this_ repo) :v

**Comment by JerichoFletcher** [comment]
For those who want to talk about MW, you can [join](https://discord.gg/3hS6JS) our Discord server.
