### ISSUE TITLE
Missing “Types”

### ISSUE THREAD

**Issue by CatSword** [JerichoFletcher/mechanical-warfare#66]
When I import this to Mindustry it is missing “types” for battleaxe, anarchy, scythe, serpent, and nullifier

**Comment by GlennFolker** [comment]
Are you on iOS platform? Scripts doesn't work in the platform.

**Comment by CatSword** [comment]
Yes. :(

**Comment by GlennFolker** [comment]
This isn't Mechanical-Warfare's issue. For some reason, mod scripts doesn't work on iOS platform, so I can't help. Sorry D:
