### ISSUE TITLE
Quarry placement

### ISSUE THREAD

**Issue by dsethlewis** [JerichoFletcher/mechanical-warfare#84]
My game crashed with the attached crash.log. Appears to be an issue with checking whether a Quarry can be placed on a tile, which is in fact what I was trying to do when the game crashed.

[crash-report-06_16_2020_08_37_09.txt](https://github.com/JerichoFletcher/mechanical-warfare/files/4786653/crash-report-06_16_2020_08_37_09.txt)

**Comment by JerichoFletcher** [comment]
Should be fixed by now
