### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by dsethlewis** [JerichoFletcher/mechanical-warfare#94]
I tried to run MW on Linux (Elementary OS, a fork of Ubuntu), and none of the scripted elements would load. Vanilla runs fine, and the non-scripted elements seem to load. I checked the log, and I can't make heads or tails of it. 

I've included a screenshot of the F8 console in-game, in case it's helpful.

![image](https://user-images.githubusercontent.com/3771538/86048252-33427500-ba1e-11ea-94b1-e917362a36f5.png)

**Comment by JerichoFletcher** [comment]
Thoughts this may be because of [this](https://github.com/Anuken/Mindustry/issues/2011). And I think this is similar to #18.
